In [1]:
import pandas as pd

In [4]:
#Pandas is an open-source Python library used for data manipulation and analysis
    #Series → one-dimensional labeled array.

#DataFrame → two-dimensional labeled data structure (like a table).
s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
print(s.name)

None

In [7]:
s.name="numbers"

In [9]:
print(s.name)

numbers

In [10]:
s

0    10
1    20
2    30
3    40
Name: numbers, dtype: int64

In [11]:
s[1]

20

In [12]:
s[0:2]

0    10
1    20
Name: numbers, dtype: int64

In [13]:
s[0:4:2]

0    10
2    30
Name: numbers, dtype: int64

In [16]:
s.iloc[[2,1,3]]

2    30
1    20
3    40
Name: numbers, dtype: int64

In [17]:
index=["amritha","anju","sushmitha","nikita"]

In [19]:
s.index=index
s

amritha      10
anju         20
sushmitha    30
nikita       40
Name: numbers, dtype: int64

In [20]:
s['nikita']

40

In [21]:
s.iloc[[1,2,3]]

anju         20
sushmitha    30
nikita       40
Name: numbers, dtype: int64

In [22]:
s.loc[['nikita','anju']]

nikita    40
anju      20
Name: numbers, dtype: int64

In [23]:
s.loc['amritha':'nikita']

amritha      10
anju         20
sushmitha    30
nikita       40
Name: numbers, dtype: int64

In [26]:
data ={
    "alluarjun":22,
    "pavan":28,
    "mahesh":30,
    "saipallavi":20,
    "nayanthara":80,
    "samantha":60,
    "anushka":50,
    "tamanna":87
}

In [28]:
s2 = pd.Series(data, name="Movies")
print(s2)

alluarjun     22
pavan         28
mahesh        30
saipallavi    20
nayanthara    80
samantha      60
anushka       50
tamanna       87
Name: Movies, dtype: int64

In [29]:
s2[(s2>25) |(s2<30)]

alluarjun     22
pavan         28
mahesh        30
saipallavi    20
nayanthara    80
samantha      60
anushka       50
tamanna       87
Name: Movies, dtype: int64

In [31]:
s2["pavan"]=29
s2

alluarjun     22
pavan         29
mahesh        30
saipallavi    20
nayanthara    80
samantha      60
anushka       50
tamanna       87
Name: Movies, dtype: int64

In [4]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, 23, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, 45000, 50000]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   35    Finance   70000
3    David   23         IT   62000
4      Eve   29         HR   45000
5    Alice   25         HR   50000

In [7]:
df.head(3)

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   35    Finance   70000

In [8]:
df.iloc[0:3,:3]

      Name  Age Department
0    Alice   25         HR
1      Bob   30         IT
2  Charlie   35    Finance

In [9]:
df.loc[1:2,["Name","Department"]]

      Name Department
1      Bob         IT
2  Charlie    Finance

In [10]:
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   35    Finance   70000
3    David   23         IT   62000
4      Eve   29         HR   45000
5    Alice   25         HR   50000

In [12]:
print(df.columns)

# Drop safely
df = df.drop("salary", axis=1, errors="ignore")

Index(['Name', 'Age', 'Department', 'Salary'], dtype='object')

In [14]:
print(df.columns.tolist())

['Name', 'Age', 'Department', 'Salary']

In [15]:
res = df.drop("salary", axis=1, errors="ignore")
print(res.shape)

(6, 4)

In [16]:
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   35    Finance   70000
3    David   23         IT   62000
4      Eve   29         HR   45000
5    Alice   25         HR   50000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         6 non-null      int64
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes

In [18]:
df.shape

(6, 4)

In [19]:
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   35    Finance   70000
3    David   23         IT   62000
4      Eve   29         HR   45000
5    Alice   25         HR   50000

In [25]:
df["Inc Salary"]=df["Salary"]+5000

In [26]:
df

      Name  Age Department  Salary  Inc Salary
0    Alice   25         HR   55000       60000
1      Bob   30         IT   65000       70000
2  Charlie   35    Finance   75000       80000
3    David   23         IT   67000       72000
4      Eve   29         HR   50000       55000
5    Alice   25         HR   55000       60000

In [23]:
df["Department"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [24]:
df["Department"].value_counts()

HR         3
IT         2
Finance    1
Name: Department, dtype: int64

In [27]:
import numpy as np

In [28]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, 23, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, np.nan, 45000, 50000]
}

In [29]:
df=pd.DataFrame(data)

In [30]:
df

      Name  Age Department   Salary
0    Alice   25         HR  50000.0
1      Bob   30         IT  60000.0
2  Charlie   35    Finance  70000.0
3    David   23         IT      NaN
4      Eve   29         HR  45000.0
5    Alice   25         HR  50000.0

In [31]:
df.dropna(how="any")

      Name  Age Department   Salary
0    Alice   25         HR  50000.0
1      Bob   30         IT  60000.0
2  Charlie   35    Finance  70000.0
4      Eve   29         HR  45000.0
5    Alice   25         HR  50000.0

      Name  Age Department   Salary
0    Alice   25         HR  50000.0
1      Bob   30         IT  60000.0
2  Charlie   35    Finance  70000.0
3    David   23         IT      NaN
4      Eve   29         HR  45000.0
5    Alice   25         HR  50000.0

In [46]:
data = {
    "Name": ["Alice", np.nan, "Charlie", "David", "np.nan", "Alice"],
    "Age": [25, np.nan, 24, 23, 29, 25],
    "Department": ["HR", np.nan, "Finance", "IT", "HR", "HR"],
    "Salary": [50000, np.nan, 70000, 60000, 45000, 50000]
}

In [47]:
df=pd.DataFrame(data)

In [48]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      NaN   NaN        NaN      NaN
2  Charlie  24.0    Finance  70000.0
3    David  23.0         IT  60000.0
4   np.nan  29.0         HR  45000.0
5    Alice  25.0         HR  50000.0

In [49]:
df.dropna(how="all")

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
2  Charlie  24.0    Finance  70000.0
3    David  23.0         IT  60000.0
4   np.nan  29.0         HR  45000.0
5    Alice  25.0         HR  50000.0

In [50]:
df["Name"]=df["Name"].replace("Alice","Amritha")
df

      Name   Age Department   Salary
0  Amritha  25.0         HR  50000.0
1      NaN   NaN        NaN      NaN
2  Charlie  24.0    Finance  70000.0
3    David  23.0         IT  60000.0
4   np.nan  29.0         HR  45000.0
5  Amritha  25.0         HR  50000.0

In [51]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "np.nan", "Alice"],
    "Age": [25, 25, 24, 23, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 35000, 70000, 60000, 45000, 50000]
}

In [52]:
df=pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   25         IT   35000
2  Charlie   24    Finance   70000
3    David   23         IT   60000
4   np.nan   29         HR   45000
5    Alice   25         HR   50000

In [54]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [55]:
df["Department"].duplicated()

0    False
1    False
2    False
3     True
4     True
5     True
Name: Department, dtype: bool

In [56]:
df = df.drop_duplicates(subset=["Department"])

In [57]:
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   25         IT   35000
2  Charlie   24    Finance   70000

In [59]:
df = df.copy()
df["Salary"] = df["Salary"].apply(lambda x: x + 10000 if x > 50000 else x)

In [60]:
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   25         IT   35000
2  Charlie   24    Finance   90000

In [61]:
data1 = {
    "ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "Salary": [45000, 55000, 60000]
}
df1 = pd.DataFrame(data1)

In [62]:
df1

   ID     Name  Salary
0   1    Alice   45000
1   2      Bob   55000
2   3  Charlie   60000

In [63]:
df_concat=pd.concat([df,df1])

In [64]:
df_concat

      Name   Age Department  Salary   ID
0    Alice  25.0         HR   50000  NaN
1      Bob  25.0         IT   35000  NaN
2  Charlie  24.0    Finance   90000  NaN
0    Alice   NaN        NaN   45000  1.0
1      Bob   NaN        NaN   55000  2.0
2  Charlie   NaN        NaN   60000  3.0

In [66]:
df = pd.read_csv(r"C:\Users\Amritha singh\Downloads\IPL_Cleaned_Data.csv")

In [67]:
df

,id,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,win_margin
0,1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,3
1,2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav,3
2,3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan,4
3,4,"March 24,2024",Rajasthan,Lucknow,Rajasthan,Bat,193,4,173,6,Rajasthan,Sanju Samson,Sanju Samson,Trent Boult,20
4,5,"March 24,2024",Gujarat,Mumbai,Mumbai,Field,168,6,162,9,Gujarat,Sai Sudharsan,Dewald Brevis,Jasprit Bumrah,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,70,"May 19,2024",Rajasthan,Kolkata,Kolkata,none,0,0,0,0,Abandoned,0,0,0,0
70,71,"May 21,2024",Hyderabad,Kolkata,Hyderabad,Bat,159,10,164,2,Kolkata,Mitchell Starc,Shreyas Iyer,Mitchell Starc,5
71,72,"May 22,2024",Banglore,Rajasthan,Rajasthan,Field,172,8,174,6,Rajasthan,Ravichandran Ashwin,Yashasvi Jaiswal,Avesh Khan,2
72,73,"May 24,2024",Hyderabad,Rajasthan,Rajasthan,Field,175,9,139,7,Hyderabad,Shahbaz Ahmed,Dhruv Jurel,Shahbaz Ahmed,36
73,74,"May 26,2024",Hyderabad,Kolkata,Hyderabad,Bat,113,10,114,2,Kolkata,Mitchell Starc,Venkatesh Iyer,Andre Russell,1

In [68]:
df.head(3)

,id,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts,win_margin
0,1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman,3
1,2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav,3
2,3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan,4

In [69]:
df.iloc[0:3,:3]

   id           date     team1
0   1  March 22,2024  Banglore
1   2  March 23,2024     Delhi
2   3  March 23,2024   Kolkata

In [70]:
df.loc[1:2,["id","team1"]]

   id    team1
1   2    Delhi
2   3  Kolkata

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   74 non-null     int64
 1   date                 74 non-null     object
 2   team1                74 non-null     object
 3   team2                74 non-null     object
 4   toss_winner          74 non-null     object
 5   decision             74 non-null     object
 6   first_score          74 non-null     int64
 7   first_wkts           74 non-null     int64
 8   second_score         74 non-null     int64
 9   second_wkts          74 non-null     int64
 10  winner               74 non-null     object
 11  player_of_the_match  74 non-null     object
 12  most_runs            74 non-null     object
 13  most_wkts            74 non-null     object
 14  win_margin           74 non-null     int64
dtypes: int64(6), object(9)
memory usage: 8.8+ KB

In [72]:
df.shape

(74, 15)